### ISSUE TITLE
Current date is not showing on weather page

### ISSUE THREAD

**Issue by kamal-y** [Jha-Shubham19/SKJ_Weather#2]

**Comment by Jha-Shubham19** [comment]
The current date not being displayed on the weather page seems to have been resolved. You can check the code at [Link](https://github.com/Jha-Shubham19/SKJ_Weather/blob/main/public/js/main.js#L77) to see that the date is now being shown. Additionally, if I recall correctly, @kamal-y was the one who successfully resolved this issue previously.

**Comment by kamal-y** [comment]
![puneet](https://github.com/Jha-Shubham19/SKJ_Weather/assets/113172623/0bbf0789-59e7-4506-8974-b694c7c7d51f)
